project:
  type: website
  output-dir: docs
website:
  title: "Nils Kottmann"
  site-url: https://nilskottmann.github.io/
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Portfolio
      - href: resume.qmd
        text: Resume
    right:
      - href: about.qmd
        text: About
      - icon: linkedin
        href: https://www.linkedin.com/in/nils-kottmann/
        text: "LinkedIn profile"
fig-format: svg
# format:
#   html:
#     theme: [cosmo, theme_light_custom.scss]
#     css: styles.css
#     toc: true
    # embed-resources: true
format:
  html:
    page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
        - mozilla.scss
    css: styles.css
    toc: false
    embed-resources: true
    self-contained-math: true

html-math-method:
  method: mathjax
  
execute: 
  freeze: auto
