project:
  type: website
  output-dir: docs
website:
  title: "Nils Kottmann"
  site-url: https://nilskottmann.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: CV
    right:
      - href: about.qmd
        text: About
      - icon: linkedin
        href: https://www.linkedin.com/in/nils-kottmann/
        text: "LinkedIn profile"
format:
  html:
    page-layout: full
    date-format: "MMM YYYY"
    theme:
      light:
        - flatly
    css: styles.css
    toc: true
    embed-resources: true
    
fig-format: svg


